### ISSUE TITLE
STD TODO List

### ISSUE THREAD

**Issue by hecmas** [0xPolygonHermez/pil2-proofman#94]
- [ ] Allow more than one bus in the same airgroup even if they are not needed for some air inside such airgroup.
- [ ] Degree function can now be used to compute the degree of an expression, use it to improve the std intermediate column generation.
- [ ] PrimeField to AbstractField.
- [ ] Allow predetermined flag in `multi_range_check` and `range_check_id` interfaces.
- [ ] Add output to file in debug mode!!!
